
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { Sitecore } from "./_.Sitecore.Override"
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentRendering, RouteData, Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { DefaultComponentProps } from '@/lib/component-props';


export namespace Project.Cipla.Sitecore.templates.Project.Cipla.Fields {
    export type AppRoute = { 
        fields?: {  
        }
 }; 
}

export namespace Project.Cipla.Sitecore.templates.Project.Cipla.Fields {
    export type HeadlessSite = { 
        fields?: {  
        }
 }; 
}

export namespace Project.Cipla.Sitecore.templates.Project.Cipla.Fields {
    export type HeadlessTenant = { 
        fields?: {  
        }
 }; 
}

export namespace Project.Cipla.Sitecore.templates.Project.Cipla.Fields {
    export type PageDesignFolder = { 
        fields?: {  
        }
 }; 
}

export namespace Project.Cipla.Sitecore.templates.Project.Cipla.Fields {
    export type PageDesigns = { 
        fields?: {  
        }
 }; 
}

export namespace Project.Cipla.Sitecore.templates.Project.Cipla.Fields {
    export type PartialDesignFolder = { 
        fields?: {  
        }
 }; 
}

export namespace Project.Cipla.Sitecore.templates.Project.Cipla.Fields {
    export type PartialDesigns = { 
        fields?: {  
        }
 }; 
}

export namespace Project.Cipla.Sitecore.templates.Project.Cipla.Breathefree.Fields {
    export type Test = { 
        fields?: { 
            /**
            * Represents the DateG field (517ed057-ca91-452c-afd3-ddae4dfa6b51).
            */
            DateG: Field<string>;

            /**
            * Represents the Description field (02a7d295-e074-4fd9-af7f-9304a27920dd).
            */
            Description: Field<string>;

            /**
            * Represents the ReletedSubjects field (cd478689-34ae-455d-833b-3d52beb609b3).
            */
            ReletedSubjects: Sitecore.Override.ItemEx[];

            /**
            * Represents the Title field (1b792151-e7d5-47d3-b1b9-128c51cfe1e0).
            */
            Title: Field<string>;

            /**
            * Represents the ToPage field (97310fe1-ef05-4257-ba4b-e5da217a189b).
            */
            ToPage: Field<string>;
 
        }
 }; 
}


